/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.classes.TipoDeVeiculos;
import persistencia.TipoDeVeiculoDAO;
import modelos.classes.StatusVeiculo;

/**
 *
 * @author artur
 */
public class Consulta extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Consulta.class.getName());

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
        jButton_Consulta.setEnabled(false);
        jTextField_Id.setEnabled(false);
        jComboBox_Marca.setEnabled(false);
        jComboBox_Status.setEnabled(false);
        carregarTabelaOriginal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Consulta_Tabela = new javax.swing.JTable();
        jComboBox_Escolha = new javax.swing.JComboBox<>();
        jButton_Consulta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jComboBox_Marca = new javax.swing.JComboBox<>();
        jComboBox_Status = new javax.swing.JComboBox<>();
        jButton_Janela_Principal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable_Consulta_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID VEICULO", "PLACA", "MARCA", "MODELO", "ANO DE FABRICAÇÃO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Consulta_Tabela);
        if (jTable_Consulta_Tabela.getColumnModel().getColumnCount() > 0) {
            jTable_Consulta_Tabela.getColumnModel().getColumn(0).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(1).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(2).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(3).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(4).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(5).setResizable(false);
        }

        jComboBox_Escolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "ID", "MARCA", "STATUS", " " }));
        jComboBox_Escolha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EscolhaActionPerformed(evt);
            }
        });

        jButton_Consulta.setText("CONSULTAR");
        jButton_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultaActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione o tipo de consulta:");

        jComboBox_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "CHEVROLET", "FIAT", "VOLKSWAGEN", "HYUNDAI", "TOYOTA", "HONDA", "RENAULT", "NISSAN", "JEEP", "CITROËN", "PEUGEOT", "MITSUBISHI", "FORD", "KIA", "BYD" }));

        jComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "ATIVO", "INATIVO" }));

        jButton_Janela_Principal.setText("PAGINA PRINCIPAL");
        jButton_Janela_Principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Janela_PrincipalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBox_Escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(342, 342, 342)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_Consulta))
                                    .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton_Janela_Principal)))
                        .addGap(0, 300, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Escolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jButton_Consulta)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButton_Janela_Principal)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_EscolhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EscolhaActionPerformed
        // TODO add your handling code here:
        String escolha = (String) jComboBox_Escolha.getSelectedItem();
        if (escolha.equals("ID")) {
            jButton_Consulta.setEnabled(true);
            jTextField_Id.setEnabled(true);
            jComboBox_Marca.setEnabled(false);
            jComboBox_Status.setEnabled(false);
        } else if (escolha.equals("STATUS")) {
            jButton_Consulta.setEnabled(true);
            jComboBox_Status.setEnabled(true);
            jTextField_Id.setEnabled(false);
            jComboBox_Marca.setEnabled(false);

        } else if (escolha.equals("MARCA")) {
            jButton_Consulta.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jTextField_Id.setEnabled(false);
            jComboBox_Status.setEnabled(false);

        } else {
            jButton_Consulta.setEnabled(false);
            jTextField_Id.setEnabled(false);
            jComboBox_Marca.setEnabled(false);
            jComboBox_Status.setEnabled(false);

        }

    }//GEN-LAST:event_jComboBox_EscolhaActionPerformed

    private void jButton_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultaActionPerformed
        // TODO add your handling code here:
        String escolha = (String) jComboBox_Escolha.getSelectedItem();
        if (escolha.equals("ID")) {
            try {
                int id = Integer.parseInt(jTextField_Id.getText());
                TipoDeVeiculoDAO dao = new TipoDeVeiculoDAO();
                TipoDeVeiculos obj = dao.buscarPorId(id);
                ArrayList<TipoDeVeiculos> lista = new ArrayList<>();
                if (obj != null) {
                    lista.add(obj);
                } else {
                    JOptionPane.showMessageDialog(null, "ID não existe");
                }
                carregarTabela(lista);

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, erro.getMessage());
            }

        } else if (escolha.equals("STATUS")) {
            try {
                StatusVeiculo status = StatusVeiculo.valueOf(jComboBox_Status.getSelectedItem().toString());

                TipoDeVeiculoDAO dao = new TipoDeVeiculoDAO();
                ArrayList<TipoDeVeiculos> lista = dao.buscarPorStatus(status);

                carregarTabela(lista);

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, erro.getMessage());
            }

        } else if (escolha.equals("MARCA")) {
            try {
                String marca = (String) jComboBox_Marca.getSelectedItem();
                TipoDeVeiculoDAO dao = new TipoDeVeiculoDAO();
                ArrayList<TipoDeVeiculos> lista = dao.buscarPorMarca(marca);
                carregarTabela(lista);

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, erro.getMessage());
            }
        }


    }//GEN-LAST:event_jButton_ConsultaActionPerformed

    private void jButton_Janela_PrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Janela_PrincipalActionPerformed
        // TODO add your handling code here:
        PaginaPrincipal janelaPrincipal = new PaginaPrincipal();
        janelaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton_Janela_PrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    private void carregarTabela(ArrayList<TipoDeVeiculos> lista) {
        try {
            // Pega o modelo da tabela
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) jTable_Consulta_Tabela.getModel();

            model.setRowCount(0); // limpa a tabela

            // Preenche a tabela apenas com a lista filtrada
            for (TipoDeVeiculos veiculo : lista) {
                model.addRow(new Object[]{
                    veiculo.getIdVeiculo(),
                    veiculo.getPlaca(),
                    veiculo.getMarca(),
                    veiculo.getModelo(),
                    veiculo.getAnoDeFabricacao(),
                    veiculo.getStatus()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    private void carregarTabelaOriginal() {
        try {
            // Pega o modelo da tabela
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) jTable_Consulta_Tabela.getModel();

            model.setRowCount(0); // limpa a tabela

            // Chama o DAO para pegar a lista de veículos
            TipoDeVeiculoDAO dao = new TipoDeVeiculoDAO();
            ArrayList<TipoDeVeiculos> lista = dao.listaDeTiposDeVeiculo();

            // Preenche a tabela
            for (TipoDeVeiculos veiculo : lista) {
                model.addRow(new Object[]{
                    veiculo.getIdVeiculo(),
                    veiculo.getPlaca(),
                    veiculo.getMarca(),
                    veiculo.getModelo(),
                    veiculo.getAnoDeFabricacao(),
                    veiculo.getStatus()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Consulta().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Consulta;
    private javax.swing.JButton jButton_Janela_Principal;
    private javax.swing.JComboBox<String> jComboBox_Escolha;
    private javax.swing.JComboBox<String> jComboBox_Marca;
    private javax.swing.JComboBox<String> jComboBox_Status;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Consulta_Tabela;
    private javax.swing.JTextField jTextField_Id;
    // End of variables declaration//GEN-END:variables
}
