/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import persistencia.TipoDeVeiculoDAO;
import modelos.classes.TipoDeVeiculos;
import modelos.classes.StatusVeiculo;
import javax.swing.JOptionPane;
import controller.Controle;
import java.util.ArrayList;

/**
 *
 * @author artur
 */
public class Editar extends javax.swing.JFrame {

    Controle cont = new Controle();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Editar.class.getName());

    /**
     * Creates new form Editar
     */
    public Editar() {
        initComponents();
        carregarTabela();
        jTextField_Id.setEnabled(false);
        jTextField_Ano.setEnabled(false);
        jTextField_Modelo.setEnabled(false);
        jTextField_Placa.setEnabled(false);
        jComboBox_Marca.setEnabled(false);
        jComboBox_Status.setEnabled(false);
        jButton_Atualizar.setEnabled(false);
        jButton_Carregar.setEnabled(false);
        jButton_Excluir.setEnabled(false);
        // Detecta clique na linha da tabela
        jTable_Consulta_Tabela.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {

                String escolha = jComboBox_Edicao.getSelectedItem().toString();

                if (escolha.equals("ATUALIZAR") || escolha.equals("EXCLUIR")) {
                    carregarCamposDaLinha();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox_Edicao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jTextField_Placa = new javax.swing.JTextField();
        jTextField_Modelo = new javax.swing.JTextField();
        jTextField_Ano = new javax.swing.JTextField();
        jComboBox_Marca = new javax.swing.JComboBox<>();
        jComboBox_Status = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton_Carregar = new javax.swing.JButton();
        jButton_Atualizar = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jButton_Adicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Consulta_Tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(47, 47, 47));

        jComboBox_Edicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "ADICIONAR", "ATUALIZAR", "EXCLUIR", " " }));
        jComboBox_Edicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EdicaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Escolha a opção desejada");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLACA");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MARCA");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("MODELO");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ANO DE FABRICA");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("STATUS");

        jTextField_Id.setBackground(new java.awt.Color(204, 204, 204));

        jTextField_Placa.setBackground(new java.awt.Color(204, 204, 204));

        jTextField_Modelo.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ModeloActionPerformed(evt);
            }
        });

        jTextField_Ano.setBackground(new java.awt.Color(204, 204, 204));

        jComboBox_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "CHEVROLET", "FIAT", "VOLKSWAGEN", "HYUNDAI", "TOYOTA", "HONDA", "RENAULT", "NISSAN", "JEEP", "CITROËN", "PEUGEOT", "MITSUBISHI", "FORD", "KIA", "BYD" }));

        jComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "ATIVO", "INATIVO" }));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID VEICULO");

        jButton_Carregar.setBackground(new java.awt.Color(11, 59, 92));
        jButton_Carregar.setText("CARREGAR");
        jButton_Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_CarregarActionPerformed(evt);
            }
        });

        jButton_Atualizar.setBackground(new java.awt.Color(11, 59, 92));
        jButton_Atualizar.setText("ATUALIZAR");
        jButton_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtualizarActionPerformed(evt);
            }
        });

        jButton_Excluir.setBackground(new java.awt.Color(11, 59, 92));
        jButton_Excluir.setText("EXCLUIR");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jButton_Adicionar.setBackground(new java.awt.Color(11, 59, 92));
        jButton_Adicionar.setText("ADICIONAR");
        jButton_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdicionarActionPerformed(evt);
            }
        });

        jTable_Consulta_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID VEICULO", "PLACA", "MARCA", "MODELO", "ANO DE FABRICAÇÃO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable_Consulta_Tabela);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox_Edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(126, 126, 126)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Placa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Adicionar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Atualizar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_Excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Carregar)))))
                .addContainerGap(410, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox_Edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jButton_Carregar)
                            .addComponent(jButton_Atualizar)
                            .addComponent(jButton_Excluir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButton_Adicionar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ModeloActionPerformed

    private void jComboBox_EdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EdicaoActionPerformed
        // TODO add your handling code here:
        String escolha = (String) jComboBox_Edicao.getSelectedItem();
        if (escolha.equals("ATUALIZAR")) {

            jTextField_Id.setEnabled(true);
            jTextField_Placa.setEnabled(true);
            jTextField_Modelo.setEnabled(true);
            jTextField_Ano.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jComboBox_Status.setEnabled(true);

            jButton_Carregar.setEnabled(true);
            jButton_Atualizar.setEnabled(true);
            jButton_Excluir.setEnabled(false);

        } else if (escolha.equals("EXCLUIR")) {

            // Só o ID deve ser
            jTextField_Id.setEnabled(true);
            jTextField_Placa.setEnabled(true);
            jTextField_Modelo.setEnabled(true);
            jTextField_Ano.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jComboBox_Status.setEnabled(true);

            jButton_Carregar.setEnabled(true);
            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(true);

        } else if (escolha.equals("ADICIONAR")) {
            jTextField_Id.setEnabled(false);
            jTextField_Placa.setEnabled(true);
            jTextField_Modelo.setEnabled(true);
            jTextField_Ano.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jComboBox_Status.setEnabled(true);

            jButton_Carregar.setEnabled(true);
            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(false);

        } else {

            jTextField_Id.setEnabled(false);
            jTextField_Placa.setEnabled(false);
            jTextField_Modelo.setEnabled(false);
            jTextField_Ano.setEnabled(false);
            jComboBox_Marca.setEnabled(false);
            jComboBox_Status.setEnabled(false);

            jButton_Carregar.setEnabled(false);
            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(false);

        }

    }//GEN-LAST:event_jComboBox_EdicaoActionPerformed

    private void jButton_CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_CarregarActionPerformed
        // TODO add your handling code here:
        try {

            // Lê textos SEM converter ainda
            String idTexto = jTextField_Id.getText().trim();
            String placaTexto = jTextField_Placa.getText().trim();

            TipoDeVeiculos obj = null;

            if (!idTexto.isEmpty()) {
                int id = Integer.parseInt(idTexto);
                obj = cont.buscarPorIdVeiculo(id);
            } else if (!placaTexto.isEmpty()) {
                obj = cont.buscarPorPlaca(placaTexto);
            } else {
                JOptionPane.showMessageDialog(null, "Digite ID ou Placa para buscar!");
                return;
            }

            if (obj == null) {
                JOptionPane.showMessageDialog(null, "Veículo não encontrado!");
                return;
            }

            jComboBox_Marca.setSelectedItem(obj.getMarca());
            jTextField_Modelo.setText(obj.getModelo());
            jTextField_Ano.setText(String.valueOf(obj.getAnoDeFabricacao()));
            jComboBox_Status.setSelectedItem(obj.getStatus().toString());
            jTextField_Placa.setText(obj.getPlaca());
            jTextField_Id.setText(String.valueOf(obj.getIdVeiculo()));

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }//GEN-LAST:event_jButton_CarregarActionPerformed

    private void jButton_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AtualizarActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextField_Id.getText());
            String placa = jTextField_Placa.getText().toUpperCase();
            String marca = jComboBox_Marca.getSelectedItem().toString();
            String modelo = jTextField_Modelo.getText().toUpperCase();
            int ano = Integer.parseInt(jTextField_Ano.getText());
            StatusVeiculo status = StatusVeiculo.valueOf(jComboBox_Status.getSelectedItem().toString());

            TipoDeVeiculos objAtualizado = new TipoDeVeiculos(
                    id, placa, marca, modelo, ano, status
            );

            cont.atualizarVeiculo(objAtualizado);
            carregarTabela();
            limparCampos();

            JOptionPane.showMessageDialog(null, "Veículo atualizado com sucesso!");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButton_AtualizarActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextField_Id.getText());

            cont.excluirVeiculo(id);
            carregarTabela();
            limparCampos();
            JOptionPane.showMessageDialog(null, "Item excluido com sucesso!");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jButton_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdicionarActionPerformed
        // TODO add your handling code here:
        try {

            String placa = jTextField_Placa.getText().toUpperCase();

            //int id = Integer.parseInt(jTextField_Id.getText());
            String marca = (String) jComboBox_Marca.getSelectedItem();
            String modelo = jTextField_Modelo.getText().toUpperCase();
            int anoDeFabricacao = Integer.parseInt(jTextField_Ano.getText());
            StatusVeiculo status = StatusVeiculo.valueOf(jComboBox_Status.getSelectedItem().toString());

            TipoDeVeiculos tipoDeVeiculo = new TipoDeVeiculos();
            tipoDeVeiculo.setPlaca(placa);
            tipoDeVeiculo.setMarca(marca);
            tipoDeVeiculo.setModelo(modelo);
            tipoDeVeiculo.setAnoDeFabricacao(anoDeFabricacao);
            tipoDeVeiculo.setStatus(status);

            Controle cont = new Controle();
            cont.adicionarVeiculo(tipoDeVeiculo);
            carregarTabela();
            limparCampos();

            JOptionPane.showMessageDialog(this, "Veiculo adicionado com sucesso!");
            carregarTabela();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }

    }//GEN-LAST:event_jButton_AdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    private void carregarTabela() {
        try {
            // Pega o modelo da tabela
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) jTable_Consulta_Tabela.getModel();
            model.setRowCount(0); // limpa a tabela

            // Chama o DAO para pegar a lista de veículos
            Controle cont = new Controle();
            ArrayList<TipoDeVeiculos> lista = cont.listar();

            // Adiciona na JTable
            for (TipoDeVeiculos v : lista) {
                model.addRow(new Object[]{
                    v.getIdVeiculo(),
                    v.getPlaca(),
                    v.getMarca(),
                    v.getModelo(),
                    v.getAnoDeFabricacao(),
                    v.getStatus()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
        }
    }

    private void carregarCamposDaLinha() {
        int linha = jTable_Consulta_Tabela.getSelectedRow();

        if (linha == -1) {
            return; // Nenhuma linha selecionada
        }

        jTextField_Id.setText(jTable_Consulta_Tabela.getValueAt(linha, 0).toString());
        jTextField_Placa.setText(jTable_Consulta_Tabela.getValueAt(linha, 1).toString());
        jComboBox_Marca.setSelectedItem(jTable_Consulta_Tabela.getValueAt(linha, 2));
        jTextField_Modelo.setText(jTable_Consulta_Tabela.getValueAt(linha, 3).toString());
        jTextField_Ano.setText(jTable_Consulta_Tabela.getValueAt(linha, 4).toString());
        jComboBox_Status.setSelectedItem(jTable_Consulta_Tabela.getValueAt(linha, 5).toString());
    }

    private void limparCampos() {
        jTextField_Id.setText("");
        jTextField_Placa.setText("");
        jTextField_Modelo.setText("");
        jTextField_Ano.setText("");
        jComboBox_Marca.setSelectedIndex(0);   // volta para "SELECIONE:"
        jComboBox_Status.setSelectedIndex(0);  // volta para "SELECIONE:"
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Editar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Adicionar;
    private javax.swing.JButton jButton_Atualizar;
    private javax.swing.JButton jButton_Carregar;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JComboBox<String> jComboBox_Edicao;
    private javax.swing.JComboBox<String> jComboBox_Marca;
    private javax.swing.JComboBox<String> jComboBox_Status;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Consulta_Tabela;
    private javax.swing.JTextField jTextField_Ano;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_Placa;
    // End of variables declaration//GEN-END:variables
}
