/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import modelos.classes.TipoDeDespesa;
import persistencia.TipoDeDespesasDAO;
import controle.TipoDespesaController;

/**
 *
 * @author Augusto
 */

public class TelaTipoDeDespesas extends javax.swing.JFrame {

  /**
   * Creates new form TelaTipoDeDespesas
   */
  public TelaTipoDeDespesas() {
        try {
            java.awt.Image icone = javax.imageio.ImageIO.read(getClass().getResource("/imagens/40X40.png"));
            this.setIconImage(icone);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null,e.getMessage());
        }
    initComponents();
    this.setLocationRelativeTo(null);
    atualizarPanelDespesas();
    
    jTableDespesas.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
        public void valueChanged(ListSelectionEvent event) {
            if(jTableDespesas.getSelectedRow() != -1){
                jTextFieldDespesa.setText(jTableDespesas.getValueAt(jTableDespesas.getSelectedRow(), 1).toString());
           }
        }
    });
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  
  private int getRamdomID(){
    Random rand = new Random();
    int numero = rand.nextInt(100); // 0 a 9
    return numero;
  }
  
  private void atualizarPanelDespesas(){ 
    try {
        String[] saida = new String[2];
        DefaultTableModel model = (DefaultTableModel) jTableDespesas.getModel();
        model.setRowCount(0);

        TipoDeDespesasDAO objDeDespesasDAO = new TipoDeDespesasDAO();
        ArrayList<TipoDeDespesa> listagem;

        listagem = objDeDespesasDAO.listaDeTiposDeDespesas();

        for(TipoDeDespesa obj : listagem){
            saida[0] = String.valueOf(obj.getIdTipoDeDespesa());
            saida[1] = String.valueOf(obj.getDescricao());
            model.addRow(saida);
        }
        jTextFieldDespesa.setText("");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Atualizar Panel - " + e.getMessage());
    }
}

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDespesas = new javax.swing.JTable();
        jTextFieldDespesa = new javax.swing.JTextField();
        jButtonAdicionarDespesa = new javax.swing.JButton();
        jButtonEditarDespesa = new javax.swing.JButton();
        jButtonRemoverDespesa = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tipo de Despesa");
        setBackground(new java.awt.Color(0, 0, 153));
        setPreferredSize(new java.awt.Dimension(680, 480));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));

        jTableDespesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO DE DESPESA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDespesas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableDespesas);
        if (jTableDespesas.getColumnModel().getColumnCount() > 0) {
            jTableDespesas.getColumnModel().getColumn(0).setMinWidth(40);
            jTableDespesas.getColumnModel().getColumn(0).setMaxWidth(40);
            jTableDespesas.getColumnModel().getColumn(1).setResizable(false);
        }

        jTextFieldDespesa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDespesaActionPerformed(evt);
            }
        });

        jButtonAdicionarDespesa.setBackground(new java.awt.Color(102, 102, 102));
        jButtonAdicionarDespesa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonAdicionarDespesa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionarDespesa.setText("ADICIONAR");
        jButtonAdicionarDespesa.setToolTipText("");
        jButtonAdicionarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarDespesaActionPerformed(evt);
            }
        });

        jButtonEditarDespesa.setBackground(new java.awt.Color(102, 102, 102));
        jButtonEditarDespesa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonEditarDespesa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonEditarDespesa.setText("EDITAR");
        jButtonEditarDespesa.setFocusPainted(false);
        jButtonEditarDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarDespesaActionPerformed(evt);
            }
        });

        jButtonRemoverDespesa.setBackground(new java.awt.Color(102, 102, 102));
        jButtonRemoverDespesa.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButtonRemoverDespesa.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRemoverDespesa.setText("REMOVER");
        jButtonRemoverDespesa.setFocusPainted(false);
        jButtonRemoverDespesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverDespesaActionPerformed(evt);
            }
        });

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo 200 x 200.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TIPO DE DESPESA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonEditarDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRemoverDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAdicionarDespesa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextFieldDespesa)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDespesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEditarDespesa)
                            .addComponent(jButtonRemoverDespesa)
                            .addComponent(jButtonAdicionarDespesa))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonRemoverDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverDespesaActionPerformed
        try{
            int linha = jTableDespesas.getSelectedRow();

            if (linha == -1) throw new Exception("Selecione um item para Remover");
            if(jTableDespesas.getSelectedRowCount() > 1) throw new Exception("Selecione apenas um item para Remover");

            TipoDespesaController controller = null;
            controller = new TipoDespesaController();

            String descricao = jTableDespesas.getValueAt(linha, 1).toString();
            int id = Integer.parseInt(jTableDespesas.getValueAt(linha, 0).toString());

            int confirm = JOptionPane.showConfirmDialog(
                null,
                "Confirma a exclusão do tipo de Despesa " + descricao +" ?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION, // Tipo de opções
                JOptionPane.QUESTION_MESSAGE
            );

            if(confirm == 0){
                controller.removerTipodeDespesa(new TipoDeDespesa(id, descricao));
            }

            atualizarPanelDespesas();

            JOptionPane.showMessageDialog(null, "Tipo de Despesa Removido");

        }catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Remover Despesa - " + erro.getMessage());
        }

    }//GEN-LAST:event_jButtonRemoverDespesaActionPerformed

    private void jButtonEditarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarDespesaActionPerformed
        // TODO add your handling code here:
        try{

            TipoDespesaController controller = null;
            controller = new TipoDespesaController();

            int linha = jTableDespesas.getSelectedRow();

            if (linha == -1) throw new Exception("Selecione um item para Editar");
            if(jTableDespesas.getSelectedRowCount() > 1) throw new Exception("Selecione apenas um item para Editar");

            String descricaoAAlterar = jTextFieldDespesa.getText();

            if(descricaoAAlterar.isEmpty()) throw new Exception("O Tipo de despesa deve ter um nome.");

            int id = Integer.parseInt(jTableDespesas.getValueAt(linha, 0).toString());

            controller.editarTipoDespesa(new TipoDeDespesa(id, descricaoAAlterar));

            atualizarPanelDespesas();

            JOptionPane.showMessageDialog(null, "Tipo de Despesa Alterado");

        }catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Editar Despesa - " + erro.getMessage());

        }

    }//GEN-LAST:event_jButtonEditarDespesaActionPerformed

    private void jButtonAdicionarDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarDespesaActionPerformed
        try {

            String descricao = jTextFieldDespesa.getText();

            if(descricao.isEmpty()) throw new Exception("O Tipo de despesa deve ter um nome.");

            TipoDespesaController controller = null;
            controller = new TipoDespesaController();

            controller.adicionarTipoDespesa(new TipoDeDespesa(getRamdomID(), descricao));

            atualizarPanelDespesas();

            JOptionPane.showMessageDialog(null, "Tipo de Despesa Adicionado");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(rootPane, "Adicionar Despesa - " + erro.getMessage());
        }
    }//GEN-LAST:event_jButtonAdicionarDespesaActionPerformed

    private void jTextFieldDespesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDespesaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldDespesaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaTipoDeDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaTipoDeDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaTipoDeDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaTipoDeDespesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TelaTipoDeDespesas().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarDespesa;
    private javax.swing.JButton jButtonEditarDespesa;
    private javax.swing.JButton jButtonRemoverDespesa;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDespesas;
    private javax.swing.JTextField jTextFieldDespesa;
    // End of variables declaration//GEN-END:variables
}
