/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import modelos.classes.TipoDeVeiculos;
import modelos.classes.StatusVeiculo;
import javax.swing.JOptionPane;
import controle.VeiculoController;
import java.util.ArrayList;

/**
 *
 * @author artur
 */
public class TelaTipoDeVeiculo extends javax.swing.JFrame {

    VeiculoController cont = new VeiculoController();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaTipoDeVeiculo.class.getName());

    /**
     * Creates new form Editar
     */
    public TelaTipoDeVeiculo() {
          try {
            java.awt.Image icone = javax.imageio.ImageIO.read(getClass().getResource("/imagens/40X40.png"));
            this.setIconImage(icone);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null,e.getMessage());
        }
        initComponents();
        this.setLocationRelativeTo(null);
        carregarTabela();
        jTextField_Id.setEnabled(false);
        jTextField_Ano.setEnabled(false);
        jTextField_Modelo.setEnabled(false);
        jTextField_Placa.setEnabled(false);
        jComboBox_Marca.setEnabled(false);
        jComboBox_Status.setEnabled(false);
        jButton_Atualizar.setEnabled(false);
        jButton_Excluir.setEnabled(false);
        jButton_Adicionar.setEnabled(false);
        
        // Detecta clique na linha da tabela
        jTable_Consulta_Tabela.getSelectionModel().addListSelectionListener(event -> {
            if (!event.getValueIsAdjusting()) {

                String escolha = jComboBox_Edicao.getSelectedItem().toString();

                if (escolha.equals("ATUALIZAR") || escolha.equals("EXCLUIR")) {
                    carregarCamposDaLinha();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jComboBox_Edicao = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Consulta_Tabela = new javax.swing.JTable();
        jButtonVoltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_Status = new javax.swing.JComboBox<>();
        jComboBox_Marca = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Placa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField_Modelo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Ano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Id = new javax.swing.JTextField();
        jButton_Atualizar = new javax.swing.JButton();
        jButton_Adicionar = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Veiculo");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 153));

        jComboBox_Edicao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "ADICIONAR", "ATUALIZAR", "EXCLUIR" }));
        jComboBox_Edicao.setToolTipText("SELECIONE:");
        jComboBox_Edicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_EdicaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ESCOLHA A OPÇÃO DESEJADA");

        jTable_Consulta_Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID VEICULO", "PLACA", "MARCA", "MODELO", "ANO DE FABRICAÇÃO", "STATUS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Consulta_Tabela.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_Consulta_Tabela);
        if (jTable_Consulta_Tabela.getColumnModel().getColumnCount() > 0) {
            jTable_Consulta_Tabela.getColumnModel().getColumn(0).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable_Consulta_Tabela.getColumnModel().getColumn(1).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(2).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(3).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(4).setResizable(false);
            jTable_Consulta_Tabela.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable_Consulta_Tabela.getColumnModel().getColumn(5).setResizable(false);
        }

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("STATUS");

        jComboBox_Status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "ATIVO", "INATIVO" }));

        jComboBox_Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONE:", "CHEVROLET", "FIAT", "VOLKSWAGEN", "HYUNDAI", "TOYOTA", "HONDA", "RENAULT", "NISSAN", "JEEP", "CITROËN", "PEUGEOT", "MITSUBISHI", "FORD", "KIA", "BYD" }));
        jComboBox_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_MarcaActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("MARCA");

        jTextField_Placa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Placa.setToolTipText("Placa");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("PLACA");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MODELO");

        jTextField_Modelo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Modelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_ModeloActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ANO");

        jTextField_Ano.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ID VEICULO");

        jTextField_Id.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jButton_Atualizar.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Atualizar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_Atualizar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Atualizar.setText("ATUALIZAR");
        jButton_Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AtualizarActionPerformed(evt);
            }
        });

        jButton_Adicionar.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Adicionar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_Adicionar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Adicionar.setText("ADICIONAR");
        jButton_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AdicionarActionPerformed(evt);
            }
        });

        jButton_Excluir.setBackground(new java.awt.Color(102, 102, 102));
        jButton_Excluir.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jButton_Excluir.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Excluir.setText("EXCLUIR");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jLabel8.setText("...");
        jLabel8.setToolTipText("");

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo 200 x 200.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Status, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(254, 254, 254))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jTextField_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_Modelo)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField_Ano)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButton_Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                        .addComponent(jComboBox_Edicao, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(550, 550, 550))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox_Edicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_Placa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField_Id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_Status)
                            .addComponent(jComboBox_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Atualizar)
                            .addComponent(jButton_Adicionar)
                            .addComponent(jButton_Excluir)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel8))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonVoltar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButton_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AdicionarActionPerformed
        // TODO add your handling code here:
        try {

            String placa = jTextField_Placa.getText().toUpperCase();

            //int id = Integer.parseInt(jTextField_Id.getText());
            String marca = (String) jComboBox_Marca.getSelectedItem();
            String modelo = jTextField_Modelo.getText().toUpperCase();
            int anoDeFabricacao = Integer.parseInt(jTextField_Ano.getText());
            StatusVeiculo status = StatusVeiculo.valueOf(jComboBox_Status.getSelectedItem().toString());

            TipoDeVeiculos tipoDeVeiculo = new TipoDeVeiculos();
            tipoDeVeiculo.setPlaca(placa);
            tipoDeVeiculo.setMarca(marca);
            tipoDeVeiculo.setModelo(modelo);
            tipoDeVeiculo.setAnoDeFabricacao(anoDeFabricacao);
            tipoDeVeiculo.setStatus(status);

            VeiculoController cont = new VeiculoController();
            cont.adicionarVeiculo(tipoDeVeiculo);
            carregarTabela();
            limparCampos();

            JOptionPane.showMessageDialog(this, "Veiculo adicionado com sucesso!");
            carregarTabela();

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButton_AdicionarActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextField_Id.getText());

            cont.excluirVeiculo(id);
            carregarTabela();
            limparCampos();
            JOptionPane.showMessageDialog(null, "Item excluido com sucesso!");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jButton_AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AtualizarActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(jTextField_Id.getText());
            String placa = jTextField_Placa.getText().toUpperCase();
            String marca = jComboBox_Marca.getSelectedItem().toString();
            String modelo = jTextField_Modelo.getText().toUpperCase();
            int ano = Integer.parseInt(jTextField_Ano.getText());
            StatusVeiculo status = StatusVeiculo.valueOf(jComboBox_Status.getSelectedItem().toString());

            TipoDeVeiculos objAtualizado = new TipoDeVeiculos(
                id, placa, marca, modelo, ano, status
            );

            cont.atualizarVeiculo(objAtualizado);
            carregarTabela();
            limparCampos();

            JOptionPane.showMessageDialog(null, "Veículo atualizado com sucesso!");

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        }
    }//GEN-LAST:event_jButton_AtualizarActionPerformed

    private void jTextField_ModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_ModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_ModeloActionPerformed

    private void jComboBox_EdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_EdicaoActionPerformed
        // TODO add your handling code here:
        String escolha = (String) jComboBox_Edicao.getSelectedItem();
        if (escolha.equals("ATUALIZAR")) {

            jTextField_Id.setEnabled(true);
            jTextField_Placa.setEnabled(true);
            jTextField_Modelo.setEnabled(true);
            jTextField_Ano.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jComboBox_Status.setEnabled(true);

            jButton_Atualizar.setEnabled(true);
            jButton_Excluir.setEnabled(false);
            jButton_Adicionar.setEnabled(false);
            limparCampos();
            
        } else if (escolha.equals("EXCLUIR")) {

            // Só o ID deve ser
            jTextField_Id.setEnabled(true);
            jTextField_Placa.setEnabled(true);
            jTextField_Modelo.setEnabled(true);
            jTextField_Ano.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jComboBox_Status.setEnabled(true);

            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(true);
            jButton_Adicionar.setEnabled(false);
            limparCampos();

        } else if (escolha.equals("ADICIONAR")) {
            jTextField_Id.setEnabled(false);
            jTextField_Placa.setEnabled(true);
            jTextField_Modelo.setEnabled(true);
            jTextField_Ano.setEnabled(true);
            jComboBox_Marca.setEnabled(true);
            jComboBox_Status.setEnabled(true);

            jButton_Adicionar.setEnabled(true);
            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(false);
            limparCampos();

        } else {

            jTextField_Id.setEnabled(false);
            jTextField_Placa.setEnabled(false);
            jTextField_Modelo.setEnabled(false);
            jTextField_Ano.setEnabled(false);
            jComboBox_Marca.setEnabled(false);
            jComboBox_Status.setEnabled(false);

            jButton_Atualizar.setEnabled(false);
            jButton_Excluir.setEnabled(false);

        }
    }//GEN-LAST:event_jComboBox_EdicaoActionPerformed

    private void jComboBox_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_MarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void carregarTabela() {
        try {
            // Pega o modelo da tabela
            javax.swing.table.DefaultTableModel model
                    = (javax.swing.table.DefaultTableModel) jTable_Consulta_Tabela.getModel();
            model.setRowCount(0); // limpa a tabela

            // Chama o DAO para pegar a lista de veículos
            VeiculoController cont = new VeiculoController();
            ArrayList<TipoDeVeiculos> lista = cont.listar();

            // Adiciona na JTable
            for (TipoDeVeiculos v : lista) {
                model.addRow(new Object[]{
                    v.getIdVeiculo(),
                    v.getPlaca(),
                    v.getMarca(),
                    v.getModelo(),
                    v.getAnoDeFabricacao(),
                    v.getStatus()
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tabela: " + e.getMessage());
        }
    }

    private void carregarCamposDaLinha() {
        int linha = jTable_Consulta_Tabela.getSelectedRow();

        if (linha == -1) {
            return; // Nenhuma linha selecionada
        }

        jTextField_Id.setText(jTable_Consulta_Tabela.getValueAt(linha, 0).toString());
        jTextField_Placa.setText(jTable_Consulta_Tabela.getValueAt(linha, 1).toString());
        jComboBox_Marca.setSelectedItem(jTable_Consulta_Tabela.getValueAt(linha, 2));
        jTextField_Modelo.setText(jTable_Consulta_Tabela.getValueAt(linha, 3).toString());
        jTextField_Ano.setText(jTable_Consulta_Tabela.getValueAt(linha, 4).toString());
        jComboBox_Status.setSelectedItem(jTable_Consulta_Tabela.getValueAt(linha, 5).toString());
    }

    private void limparCampos() {
        jTextField_Id.setText("");
        jTextField_Placa.setText("");
        jTextField_Modelo.setText("");
        jTextField_Ano.setText("");
        jComboBox_Marca.setSelectedIndex(0);   // volta para "SELECIONE:"
        jComboBox_Status.setSelectedIndex(0);  // volta para "SELECIONE:"
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaTipoDeVeiculo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JButton jButton_Adicionar;
    private javax.swing.JButton jButton_Atualizar;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JComboBox<String> jComboBox_Edicao;
    private javax.swing.JComboBox<String> jComboBox_Marca;
    private javax.swing.JComboBox<String> jComboBox_Status;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_Consulta_Tabela;
    private javax.swing.JTextField jTextField_Ano;
    private javax.swing.JTextField jTextField_Id;
    private javax.swing.JTextField jTextField_Modelo;
    private javax.swing.JTextField jTextField_Placa;
    // End of variables declaration//GEN-END:variables
}
